### ISSUE TITLE
Custom CSS disabled/causing issues

### ISSUE THREAD

**Issue by jelle619** [gonativeio/gonative-android#10]
On Android, when having custom CSS changes in the app itself, it causes CSS to get disabled when logging in on a Wordpress enabled website. When using Crosswalk, instead of disabling the CSS loggin in completely stops working.

**Comment by snyderj** [comment]
Sorry for this issue. We've found the combination of Custom CSS, Crosswalk webview, and Login POST requests have small issues with some websites. Please see "Server-side option" at https://gonative.io/docs#custom-css for workaround.
