### ISSUE TITLE
Bug: Custom CSS is not applied after Form Submissions

### ISSUE THREAD

**Issue by simplexx** [gonativeio/gonative-android#12]
After a Form is submitted, the Custom CSS is not applied on the next Page.

For Example:
A User sends a contact form, on the thank you page, the Custom CSS is not applied.

To reproduce:
1. Compile the android app with the following settings:
"initialUrl": "http://jkorpela.fi/forms/testing.html",
"customCSS": "h1 {\ndisplay: none ! important;\n}",

2. Run the app, and note that the h1 title is hidden on the loaded website.

3. Then simply click the send button on the first form

4. On the next page, you will see that the h1 Title is visible, which is unexpected.

**Comment by simplexx** [comment]
Any updates regarding this issue?

**Comment by snyderj** [comment]
Hi simplexx, sorry for delay. We believe the issue occurs with custom css when there is POST and GET request to same URLs. Please see "Server-side option" at https://gonative.io/docs#custom-css as workaround. 

In future, you may reach our support at hello at gonative dot io for faster service. 

Thanks,
John
