### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by atasoyh** [gonativeio/gonative-android#13]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processNormalGenericDebugAndroidTestResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

Have you seen this problem?

Starting process 'command 'C:\Users\ataso.DELL\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe''. Working directory:...\android\app Command: C:\Users\ataso.DELL\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe package -f --no-crunch -I C:\Users\ataso.DELL\AppData\Local\Android\Sdk\platforms\android-26\android.jar -M ...\android\app\build\intermediates\manifest\androidTest\xwalkGeneric\debug\AndroidManifest.xml -S ...\android\app\build\intermediates\res\merged\androidTest\xwalkGeneric\debug -m -J ...\android\app\build\generated\source\r\androidTest\xwalkGeneric\debug -F ...\android\app\build\intermediates\res\resources-xwalk-generic-debug-androidTest.ap_ --debug-mode -0 apk --no-version-vectors
Successfully started process 'command 'C:\Users\ataso.DELL\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe''
:app:processXwalkGenericDebugAndroidTestResources FAILED
:app:processXwalkGenericDebugAndroidTestResources (Thread[Daemon worker Thread 5,5,main]) completed. Took 2.264 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processXwalkGenericDebugAndroidTestResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by atasoyh** [comment]
If I update versions of buildtools, gradle, libraries. I face with this problem! 

```
import android.support.v7.app.ActionBarActivity;
                             ^
  symbol:   class ActionBarActivity
  location: package android.support.v7.app
```

**Comment by snyderj** [comment]
Please email our support email address hello at gonative dot io and we'd be happy to help you resolve this issue.
