### ISSUE TITLE
Gonative Not Load Data

### ISSUE THREAD

**Issue by mbahgoogle** [gonativeio/gonative-android#14]
Gonative does not display data in the table, before it can run properly. What should I do? does the web block to be able to display data gonatively. data can be displayed in the default browser and chrome.

Like capture below

## Capture Gonative

![screenshot_2018-09-22-08-20-48-19](https://user-images.githubusercontent.com/32528020/45921161-dce6f080-be9f-11e8-856f-b1c5772fcebf.png)

## Default Browser 

![screenshot_2018-09-23-02-39-56-02](https://user-images.githubusercontent.com/32528020/45921165-e83a1c00-be9f-11e8-8090-ed8f858c71c8.png)

Android that I use: 5.1.1

Thanks.

**Comment by snyderj** [comment]
@mbahgoogle Have you found a solution to your issue yet? Please check SSL issues on API data endpoint. You may also debug your website running within your app using remote debugging technique at http://support.gonative.io/knowledge_base/topics/how-can-i-debug-my-website-running-inside-my-android-and-ios-apps
