### ISSUE TITLE
Localize offline.html

### ISSUE THREAD

**Issue by ofrias** [gonativeio/gonative-android#15]
Currently offline.html displays the error message in English, if you replace it by this code it will support 7 languages:

At the head:

    <meta charset="utf-8">

Instead of the hardcoded message:

    <script type="text/javascript">
    var userLang = navigator.language || navigator.userLanguage;
    if (userLang.indexOf("es") == 0) {
        document.write("<p>No hay conexión a Internet.<br>Conéctate y vuelve a intentarlo.</p>");
    } else if (userLang.indexOf("ca") == 0) {
        document.write("<p>No hi ha connexió a Internet.<br>Connecta't i torna-ho a provar.</p>");
    } else if (userLang.indexOf("de") == 0) {
        document.write("<p>Keine Internetverbindung.<br>Verbinden Sie sich und versuchen Sie es erneut.</p>");
    } else if (userLang.indexOf("fr") == 0) {
        document.write("<p>Pas de connexion Internet.<br>Connectez-vous et essayez à nouveau.</p>");
    } else if (userLang.indexOf("it") == 0) {
        document.write("<p>Nessuna connessione Internet.<br>Connettiti e riprova.</p>");
    } else if (userLang.indexOf("pt") == 0) {
        document.write("<p>Sem conexão com a internet.<br>Conecte-se e tente novamente.</p>");
    } else {
        document.write("<p>No Internet connection.<br>Connect and try again.</p>");
    }
    </script>

**Comment by snyderj** [comment]
Hi @ofrias - Thanks for the suggestion. For now you may make local modification to offline.html in the downloaded source code. We will look into adding this in a future update.
