### ISSUE TITLE
Navigation timeout in single-page applications

### ISSUE THREAD

**Issue by ewdicus** [gonativeio/gonative-android#20]
Hello,

It looks like this commit (https://github.com/gonativeio/gonative-android/commit/68141b54c268de8075b7ea90840a54ac84fc8d1e) introduced a timeout in `URLNavigation` `shouldOverrideUrlLoading` method:
https://github.com/gonativeio/gonative-android/commit/68141b54c268de8075b7ea90840a54ac84fc8d1e#diff-c5961d25b9e89b56003cab12b26a941fR765-R774

 It looks like the intention is to clear this when `onPageStarted` is fired:
https://github.com/gonativeio/gonative-android/commit/68141b54c268de8075b7ea90840a54ac84fc8d1e#diff-c5961d25b9e89b56003cab12b26a941fR781

I'm experiencing a problem in a single-page (using react and react-router) that's reproducible as follows:
1. Navigate forward in a single-page app
2. Swipe back or hit the Android back button (depending on the version of Android and the OS navigation settings).
3. Wait 10 seconds for the timeout to fire and show the offline page.

It's not clear to me what edge-case the timeout is protecting against, so I'm not sure what the appropriate fix is, but it's worth noting I've seen suggestions to use `doUpdateVisitedHistory` instead of `onPageStarted` when dealing with single-page applications - if I add a `Log` there I do see the urls as I navigate around.

I noticed there's a comment in `addToHistory` talking about `onPageStarted` not being called which I think is the same problem being solved, but for a different case: https://github.com/gonativeio/gonative-android/blob/gonative-public/app/src/main/java/io/gonative/android/MainActivity.java#L589-L591

Thanks!

**Comment by weiyin** [comment]
Thanks for the detailed report! We have deployed a fix in a481c653f67de3a1131f14eba64e9e999dc4328b
