### ISSUE TITLE
How to disable zoom?

### ISSUE THREAD

**Issue by MindfulMe** [gonativeio/gonative-android#24]
Expected behavior to not have ability to zoom text closer like on native mobile apps

**Comment by snyderj** [comment]
Hi, 

Please see:
1. https://support.gonative.io/help/how-to-disable-android-system-font-scaling-or-set-a-specific-scale
2. https://support.gonative.io/help/how-do-i-re-enable-pinch-zoom-in-my-app

Thanks,
John
