### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by adrlab** [gonativeio/gonative-android#3]
Hi, when i enter my login credential and click on login button, the page reload but i am not log in.

**Comment by itsamoreh** [comment]
Having the same issue.

It looks like having Custom CSS in GoNative changes the login action from a GET to a POST. When I remove custom CSS the form POSTS properly.

I heard from GoNative that they're upgrading to the latest version of Crosswalk so hopefully that will resolve this bug.

**Comment by Aliceeebr** [comment]
Speaking about great native apps,i'd also recommend you an app called AmazingCart which is a Unique Ready Native Mobile application for your Online Store. You only need to choose the theme, name and the logo. Install the plugin into your CMS (WooCommerce, Magento, Opencart and PrestaShop). No coding skills required! Our support team will help you every step of the way from setting up the application to uploading it to AppStore or Google Play. Quick installation in few clicks, modern design and interface, free updates, no monthly fee, regular content update!
Try demo right now!
http://amazingcart.us/

**Comment by speedily** [comment]
thats not an issue, I did it with jquery. try a bit harder.

**Comment by snyderj** [comment]
We have not received any further reports of this issue. Please contact support if you are still having any problem with this.
