### ISSUE TITLE
Third-party cookies issue

### ISSUE THREAD

**Issue by sdboer78** [gonativeio/gonative-android#4]
Because the new cookie policy on Lollipop en higher we have to explicit set accept-third-party-cookies:

```
if (Build.VERSION.SDK_INT >= 21) {
       // https://developer.android.com/reference/android/webkit/CookieManager.html#setAcceptThirdPartyCookies(android.webkit.WebView, boolean)
       CookieManager.getInstance().setAcceptThirdPartyCookies(webView, true);
}
```

In my case, I have a external Cookie Consent implementation which set a own cookie. Because that cookie is blocked by Lollipop the Consent message does not disappear.

**Comment by weiyin** [comment]
Thanks, added to 3c3d53f07b36ef53f8b7caa47f8fcf9f8c959ff8.
