### ISSUE TITLE
Referer header missing in http request

### ISSUE THREAD

**Issue by sdboer78** [gonativeio/gonative-android#6]
The referer header is missing in the http requests in the webviews. 

In my case my cookie consent module cannot redirect my correctly back, when I consent.
https://gist.github.com/sdboer78/0a91a7d8b91c5e47e8acfd930a83eec3

System: android 6.0.1

**Comment by weiyin** [comment]
Just released a fix in 3c3d53f07b36ef53f8b7caa47f8fcf9f8c959ff8.
